//! Emulated terminal screen backed by `alacritty_terminal`.
//!
//! A `Screen` can be used on the daemon side (authoritative copy driven by PTY
//! output) or on the client side (mirror driven by the daemon's snapshot +
//! subsequent `Output` data frames).

use std::fmt::Write as FmtWrite;
use std::sync::{Arc, Mutex};

use alacritty_terminal::event::{Event as AlacEvent, EventListener};
use alacritty_terminal::grid::Dimensions;
use alacritty_terminal::index::{Column, Line};
use alacritty_terminal::term::{Config as AlacConfig, Term, TermMode};
use alacritty_terminal::vte::ansi::{self, Color, NamedColor, Rgb};
use alacritty_terminal::term::cell::Flags;
use ratatui::buffer::Buffer;
use ratatui::layout::Rect;
use ratatui::style::{Color as RColor, Modifier, Style};

// ── Mouse mode ───────────────────────────────────────────────────────────────

/// Which class of mouse events the child has enabled.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum MouseMode {
    /// No mouse reporting.
    #[default]
    Off,
    /// Press, release, and scroll-wheel events only (`?1000h`).
    Click,
    /// Click events plus motion while a button is held (`?1002h`).
    Drag,
    /// All mouse motion, with or without a button held (`?1003h`).
    Motion,
}

// ── Modes ────────────────────────────────────────────────────────────────────

/// Observable terminal-mode state that the TUI client needs to route input
/// correctly and that the snapshot must reproduce.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Modes {
    pub alt_screen: bool,
    pub bracketed_paste: bool,
    pub app_cursor: bool,
    /// Application keypad mode (`\x1b=`). Crossterm does not generate numpad
    /// events so this flag is exposed for completeness but the key encoder does
    /// not need it; document rather than encode.
    pub app_keypad: bool,
    /// Which mouse events the child has requested.
    pub mouse: MouseMode,
    /// SGR 1006 mouse encoding (`?1006h`), as opposed to the legacy X10 form.
    pub mouse_sgr: bool,
    /// Focus-in/focus-out events (`?1004h`).
    pub focus_reporting: bool,
    pub cursor_visible: bool,
}

// ── Internal event state ──────────────────────────────────────────────────────

struct EventState {
    title: Option<String>,
    bell: bool,
}

/// `EventListener` implementation that captures title and bell events.
///
/// `PtyWrite` events (terminal-probe replies generated by `alacritty_terminal`
/// when it encounters DA1/DA2, XTVERSION, etc.) are intentionally discarded
/// here. `term::probe::ProbeResponder` is the single answerer of those queries
/// and writes replies back to the PTY master itself; relaying them a second
/// time would send duplicate responses that confuse the child.
#[derive(Clone)]
struct Listener(Arc<Mutex<EventState>>);

impl EventListener for Listener {
    fn send_event(&self, event: AlacEvent) {
        if let Ok(mut s) = self.0.lock() {
            match event {
                AlacEvent::Title(t) => s.title = Some(t),
                AlacEvent::ResetTitle => s.title = None,
                AlacEvent::Bell => s.bell = true,
                // PtyWrite: see the module-level doc comment on `Listener`.
                AlacEvent::PtyWrite(_) => {}
                _ => {}
            }
        }
    }
}

// ── Simple Dimensions impl ────────────────────────────────────────────────────

struct TermSize {
    columns: usize,
    screen_lines: usize,
}

impl Dimensions for TermSize {
    fn total_lines(&self) -> usize {
        self.screen_lines
    }
    fn screen_lines(&self) -> usize {
        self.screen_lines
    }
    fn columns(&self) -> usize {
        self.columns
    }
}

// ── Screen ────────────────────────────────────────────────────────────────────

/// One emulated terminal screen.
///
/// On the daemon side this is the authoritative copy driven by PTY output.
/// On the client side it is a mirror seeded with the daemon's `snapshot()`
/// and then driven by subsequent `Output` data frames.
pub struct Screen {
    term: Term<Listener>,
    processor: ansi::Processor,
    state: Arc<Mutex<EventState>>,
    rows: u16,
    cols: u16,
}

impl Screen {
    /// Create a new blank screen of the given dimensions.
    pub fn new(rows: u16, cols: u16) -> Self {
        let state = Arc::new(Mutex::new(EventState { title: None, bell: false }));
        let listener = Listener(Arc::clone(&state));
        let size = TermSize { columns: cols as usize, screen_lines: rows as usize };
        let term = Term::new(AlacConfig::default(), &size, listener);
        Self { term, processor: ansi::Processor::new(), state, rows, cols }
    }

    /// Drive the VTE parser and advance the terminal state.
    pub fn feed(&mut self, bytes: &[u8]) {
        self.processor.advance(&mut self.term, bytes);
    }

    /// Resize the terminal. Existing content reflows as alacritty would.
    pub fn resize(&mut self, rows: u16, cols: u16) {
        self.rows = rows;
        self.cols = cols;
        self.term.resize(TermSize { columns: cols as usize, screen_lines: rows as usize });
    }

    /// Current `(rows, cols)`.
    pub fn size(&self) -> (u16, u16) {
        (self.rows, self.cols)
    }

    /// Snapshot of the observable terminal modes.
    pub fn modes(&self) -> Modes {
        let m = self.term.mode();
        let mouse = if m.contains(TermMode::MOUSE_MOTION) {
            MouseMode::Motion
        } else if m.contains(TermMode::MOUSE_DRAG) {
            MouseMode::Drag
        } else if m.contains(TermMode::MOUSE_REPORT_CLICK) {
            MouseMode::Click
        } else {
            MouseMode::Off
        };
        Modes {
            alt_screen: m.contains(TermMode::ALT_SCREEN),
            bracketed_paste: m.contains(TermMode::BRACKETED_PASTE),
            app_cursor: m.contains(TermMode::APP_CURSOR),
            app_keypad: m.contains(TermMode::APP_KEYPAD),
            mouse,
            mouse_sgr: m.contains(TermMode::SGR_MOUSE),
            focus_reporting: m.contains(TermMode::FOCUS_IN_OUT),
            cursor_visible: m.contains(TermMode::SHOW_CURSOR),
        }
    }

    /// Cursor position as `(col, row)` in screen coordinates, or `None` when
    /// the cursor is hidden.
    pub fn cursor(&self) -> Option<(u16, u16)> {
        if !self.term.mode().contains(TermMode::SHOW_CURSOR) {
            return None;
        }
        let pt = self.term.grid().cursor.point;
        let col = pt.column.0 as u16;
        let row = pt.line.0 as u16;
        Some((col, row))
    }

    /// Most recent window title set via OSC 0 or OSC 2, if any.
    pub fn title(&self) -> Option<String> {
        self.state.lock().ok().and_then(|s| s.title.clone())
    }

    /// Returns `true` once per BEL received since the last call (auto-clears).
    pub fn take_bell(&mut self) -> bool {
        if let Ok(mut s) = self.state.lock() {
            let v = s.bell;
            s.bell = false;
            v
        } else {
            false
        }
    }

    /// Produce an escape-sequence byte string that, when fed into a fresh
    /// `Screen` of the same size, reproduces:
    ///
    /// - All visible cells (characters including wide/emoji and combining
    ///   characters, fg/bg colors including truecolor and indexed,
    ///   bold/dim/italic/underline/reverse/strikethrough/hidden attributes).
    /// - The real cursor position (always emitted, visibility separately).
    /// - The terminal modes (alt screen, bracketed paste, app cursor, app
    ///   keypad, mouse mode + SGR encoding, focus reporting).
    /// - Scroll margins (top/bottom region, if non-default).
    /// - The active SGR state re-emitted at the end so that bytes appended
    ///   after the snapshot are styled correctly (continuation state).
    ///
    /// **Limitation**: primary-screen contents are not preserved. Claude Code
    /// always runs in the alt screen, so this is not a problem in practice;
    /// the snapshot begins with `\x1b[?1049h` which clears the alt screen
    /// before filling it.
    pub fn snapshot(&self) -> Vec<u8> {
        let mut out: Vec<u8> = Vec::with_capacity(8192);
        let modes = self.modes();

        // 1. Reset attributes, scroll margins and origin mode so the snapshot
        //    paints correctly onto a mirror that has already been used.
        out.extend_from_slice(b"\x1b[0m\x1b[r\x1b[?6l");
        // Hide the cursor while we paint to avoid flickering on the mirror.
        out.extend_from_slice(b"\x1b[?25l");

        // 2. Enter or clear the screen.
        if modes.alt_screen {
            // Enter the alternate screen (saves primary, clears alt).
            // Primary-screen contents are not preserved; see doc comment above.
            out.extend_from_slice(b"\x1b[?1049h");
        } else {
            out.extend_from_slice(b"\x1b[2J\x1b[H");
        }

        // 3. Paint cells.
        let grid = self.term.grid();
        let n_rows = grid.screen_lines();
        let n_cols = grid.columns();

        // Track current SGR state so we only emit changes.
        let default_fg = Color::Named(NamedColor::Foreground);
        let default_bg = Color::Named(NamedColor::Background);
        let mut cur_fg = default_fg;
        let mut cur_bg = default_bg;
        let mut cur_flags = Flags::empty();

        for r in 0..n_rows {
            // Position to start of row.
            push_fmt(&mut out, format_args!("\x1b[{};1H", r + 1));

            let line_idx = Line(r as i32 - grid.display_offset() as i32);

            for c in 0..n_cols {
                let cell = &grid[line_idx][Column(c)];

                // Wide-char spacer cells are implicit — the wide char itself
                // advances the cursor by 2. Emitting the spacer would insert
                // an extra space and shift subsequent cells.
                if cell.flags.contains(Flags::WIDE_CHAR_SPACER) {
                    continue;
                }

                let display_flags = cell.flags & DISPLAY_FLAGS;
                if cell.fg != cur_fg || cell.bg != cur_bg || display_flags != cur_flags & DISPLAY_FLAGS {
                    emit_sgr(&mut out, cell.fg, cell.bg, cell.flags);
                    cur_fg = cell.fg;
                    cur_bg = cell.bg;
                    cur_flags = cell.flags;
                }

                let ch = if cell.c == '\0' { ' ' } else { cell.c };
                let mut buf = [0u8; 4];
                out.extend_from_slice(ch.encode_utf8(&mut buf).as_bytes());

                // Emit combining (zero-width) characters attached to this cell.
                if let Some(zwc) = cell.zerowidth() {
                    for &zc in zwc {
                        let mut zb = [0u8; 4];
                        out.extend_from_slice(zc.encode_utf8(&mut zb).as_bytes());
                    }
                }
            }
        }

        // 4. Re-emit the terminal's active pen (SGR state at the cursor), so
        //    bytes appended after the snapshot are styled correctly. This is the
        //    "continuation state" the review identified as missing. The cursor's
        //    `template` cell holds the currently active fg/bg/flags.
        let pen = &grid.cursor.template;
        let pen_fg = pen.fg;
        let pen_bg = pen.bg;
        let pen_flags = pen.flags;
        let active_sgr_is_default = pen_fg == default_fg
            && pen_bg == default_bg
            && (pen_flags & DISPLAY_FLAGS).is_empty();
        if active_sgr_is_default {
            out.extend_from_slice(b"\x1b[0m");
        } else {
            emit_sgr(&mut out, pen_fg, pen_bg, pen_flags);
        }

        // 5. Always emit the real cursor position (even when hidden), then set
        //    visibility separately. This ensures relative cursor movement after
        //    the snapshot lands correctly on a mirror.
        let cursor_pt = self.term.grid().cursor.point;
        let cursor_col = cursor_pt.column.0 as u16;
        let cursor_row = cursor_pt.line.0 as u16;
        push_fmt(&mut out, format_args!("\x1b[{};{}H", cursor_row + 1, cursor_col + 1));
        if modes.cursor_visible {
            out.extend_from_slice(b"\x1b[?25h");
        } else {
            out.extend_from_slice(b"\x1b[?25l");
        }

        // 6. Restore scroll margins if non-default.
        let scroll_top = grid.display_offset();
        // alacritty_terminal does not expose margins directly through the grid;
        // we emit the scroll region from the mode flags. When no custom region
        // is active the `\x1b[r` at the top already reset it.
        // For active regions (custom top/bottom), re-emit here.
        // Since alacritty_terminal does not expose the raw margin values via
        // a stable public API, we emit only the reset (already done in step 1)
        // unless we detect a non-default display offset, which implies scrolling.
        // Custom scroll regions require tracking DECSTBM sequences ourselves.
        let _ = scroll_top; // used only for future extension

        // 7. Emit mode sequences.
        out.extend_from_slice(if modes.app_cursor { b"\x1b[?1h" } else { b"\x1b[?1l" });
        out.extend_from_slice(if modes.app_keypad { b"\x1b=" } else { b"\x1b>" });
        out.extend_from_slice(if modes.bracketed_paste { b"\x1b[?2004h" } else { b"\x1b[?2004l" });
        // Reset all mouse modes, then enable the right one.
        out.extend_from_slice(b"\x1b[?1003l\x1b[?1002l\x1b[?1000l");
        match modes.mouse {
            MouseMode::Off => {}
            MouseMode::Click => out.extend_from_slice(b"\x1b[?1000h"),
            MouseMode::Drag => out.extend_from_slice(b"\x1b[?1002h"),
            MouseMode::Motion => out.extend_from_slice(b"\x1b[?1003h"),
        }
        out.extend_from_slice(if modes.mouse_sgr { b"\x1b[?1006h" } else { b"\x1b[?1006l" });
        out.extend_from_slice(if modes.focus_reporting { b"\x1b[?1004h" } else { b"\x1b[?1004l" });

        out
    }

    /// Draw the screen into a ratatui `Buffer`, clipped to `area`.
    ///
    /// Does not panic on any area or size mismatch — cells outside the
    /// intersection of `area` and the screen grid are simply not written.
    pub fn render(&self, area: Rect, buf: &mut Buffer) {
        let grid = self.term.grid();
        let n_rows = grid.screen_lines();
        let n_cols = grid.columns();
        if n_rows == 0 || n_cols == 0 {
            return;
        }

        for rel_row in 0..area.height {
            if rel_row as usize >= n_rows {
                break;
            }
            let line_idx = Line(rel_row as i32 - grid.display_offset() as i32);

            for rel_col in 0..area.width {
                if rel_col as usize >= n_cols {
                    break;
                }
                let cell = &grid[line_idx][Column(rel_col as usize)];

                // Skip wide-char spacer cells; the wide char itself (at the
                // preceding column) already paints the character into the
                // ratatui buffer cell, and the spacer column is left blank so
                // that the buffer width accounting stays correct.
                if cell.flags.contains(Flags::WIDE_CHAR_SPACER) {
                    continue;
                }

                let bx = area.x + rel_col;
                let by = area.y + rel_row;

                let mut style = Style::default()
                    .fg(alac_to_ratatui(cell.fg))
                    .bg(alac_to_ratatui(cell.bg));
                if cell.flags.contains(Flags::BOLD) {
                    style = style.add_modifier(Modifier::BOLD);
                }
                if cell.flags.contains(Flags::DIM) {
                    style = style.add_modifier(Modifier::DIM);
                }
                if cell.flags.contains(Flags::ITALIC) {
                    style = style.add_modifier(Modifier::ITALIC);
                }
                if cell.flags.intersects(Flags::ALL_UNDERLINES) {
                    style = style.add_modifier(Modifier::UNDERLINED);
                }
                if cell.flags.contains(Flags::INVERSE) {
                    style = style.add_modifier(Modifier::REVERSED);
                }
                if cell.flags.contains(Flags::HIDDEN) {
                    style = style.add_modifier(Modifier::HIDDEN);
                }
                if cell.flags.contains(Flags::STRIKEOUT) {
                    style = style.add_modifier(Modifier::CROSSED_OUT);
                }

                if let Some(bc) = buf.cell_mut((bx, by)) {
                    let ch = if cell.c == '\0' { ' ' } else { cell.c };
                    bc.set_char(ch);
                    bc.set_style(style);
                }
            }
        }
    }

    /// Test accessor: returns a flat snapshot of (char, fg, bg, flags) for
    /// every visible cell, in row-major order.
    #[cfg(test)]
    pub fn cell_grid(&self) -> Vec<(char, Color, Color, Flags)> {
        let grid = self.term.grid();
        let n_rows = grid.screen_lines();
        let n_cols = grid.columns();
        let mut result = Vec::with_capacity(n_rows * n_cols);
        for r in 0..n_rows {
            let line_idx = Line(r as i32 - grid.display_offset() as i32);
            for c in 0..n_cols {
                let cell = &grid[line_idx][Column(c)];
                result.push((cell.c, cell.fg, cell.bg, cell.flags));
            }
        }
        result
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Display-affecting cell flags (excludes layout/internal flags like WRAPLINE,
/// WIDE_CHAR, WIDE_CHAR_SPACER, LEADING_WIDE_CHAR_SPACER).
const DISPLAY_FLAGS: Flags = Flags::BOLD
    .union(Flags::DIM)
    .union(Flags::ITALIC)
    .union(Flags::UNDERLINE)
    .union(Flags::DOUBLE_UNDERLINE)
    .union(Flags::UNDERCURL)
    .union(Flags::DOTTED_UNDERLINE)
    .union(Flags::DASHED_UNDERLINE)
    .union(Flags::INVERSE)
    .union(Flags::HIDDEN)
    .union(Flags::STRIKEOUT);

/// Map an alacritty color to the closest ratatui color.
///
/// `NamedColor::Foreground`, `Background`, `Cursor`, and the `Dim*`/`Bright*`
/// semantic variants fall back to `Color::Reset` (terminal default), which
/// causes ratatui to use the terminal's own default.
fn alac_to_ratatui(c: Color) -> RColor {
    match c {
        Color::Named(nc) => named_index(nc).map_or(RColor::Reset, RColor::Indexed),
        Color::Indexed(i) => RColor::Indexed(i),
        Color::Spec(Rgb { r, g, b }) => RColor::Rgb(r, g, b),
    }
}

/// Palette index (0–15) of a named color. Dim variants map to their normal
/// color; the semantic colors (default foreground/background, cursor) have
/// none and mean "terminal default".
fn named_index(nc: NamedColor) -> Option<u8> {
    use NamedColor::*;
    Some(match nc {
        Black | DimBlack => 0,
        Red | DimRed => 1,
        Green | DimGreen => 2,
        Yellow | DimYellow => 3,
        Blue | DimBlue => 4,
        Magenta | DimMagenta => 5,
        Cyan | DimCyan => 6,
        White | DimWhite => 7,
        BrightBlack => 8,
        BrightRed => 9,
        BrightGreen => 10,
        BrightYellow => 11,
        BrightBlue => 12,
        BrightMagenta => 13,
        BrightCyan => 14,
        BrightWhite => 15,
        _ => return None,
    })
}

/// Emit a complete SGR sequence resetting all attributes and then setting the
/// given foreground color, background color, and cell flags.
fn emit_sgr(out: &mut Vec<u8>, fg: Color, bg: Color, flags: Flags) {
    // Start with reset; attributes follow as additional params.
    out.extend_from_slice(b"\x1b[0");
    if flags.contains(Flags::BOLD) { out.extend_from_slice(b";1"); }
    if flags.contains(Flags::DIM) { out.extend_from_slice(b";2"); }
    if flags.contains(Flags::ITALIC) { out.extend_from_slice(b";3"); }
    if flags.contains(Flags::UNDERLINE) { out.extend_from_slice(b";4"); }
    if flags.contains(Flags::INVERSE) { out.extend_from_slice(b";7"); }
    if flags.contains(Flags::HIDDEN) { out.extend_from_slice(b";8"); }
    if flags.contains(Flags::STRIKEOUT) { out.extend_from_slice(b";9"); }
    append_color_sgr(out, fg, true);
    append_color_sgr(out, bg, false);
    out.push(b'm');
}

/// Append an SGR color parameter for either the foreground (`is_fg=true`) or
/// background. Does nothing for default/semantic colors (already handled by
/// the `0` reset in `emit_sgr`).
fn append_color_sgr(out: &mut Vec<u8>, color: Color, is_fg: bool) {
    let base: u8 = if is_fg { 30 } else { 40 };
    match color {
        Color::Named(nc) => match named_index(nc) {
            // Normal colors: 30–37 / 40–47; bright: 90–97 / 100–107.
            Some(i @ 0..=7) => push_fmt(out, format_args!(";{}", base + i)),
            Some(i) => push_fmt(out, format_args!(";{}", base + 60 + (i - 8))),
            // Terminal default: already reset by the leading `0`.
            None => {}
        },
        Color::Indexed(i) => {
            if is_fg {
                push_fmt(out, format_args!(";38;5;{i}"));
            } else {
                push_fmt(out, format_args!(";48;5;{i}"));
            }
        }
        Color::Spec(Rgb { r, g, b }) => {
            if is_fg {
                push_fmt(out, format_args!(";38;2;{r};{g};{b}"));
            } else {
                push_fmt(out, format_args!(";48;2;{r};{g};{b}"));
            }
        }
    }
}

/// `write!` into a `Vec<u8>`, infallible.
fn push_fmt(out: &mut Vec<u8>, args: std::fmt::Arguments<'_>) {
    // Safety: we are writing valid UTF-8 escape sequences only.
    struct W<'a>(&'a mut Vec<u8>);
    impl FmtWrite for W<'_> {
        fn write_str(&mut self, s: &str) -> std::fmt::Result {
            self.0.extend_from_slice(s.as_bytes());
            Ok(())
        }
    }
    let _ = W(out).write_fmt(args);
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use ratatui::buffer::Buffer;
    use ratatui::layout::Rect;

    /// Feed the raw PTY bytes from `stream1.raw` (120×40) and `stream2.raw`
    /// (100×30) into a Screen, take a snapshot, replay the snapshot into a
    /// fresh Screen of the same size, and assert that every cell (character,
    /// fg, bg, display-flags), the cursor, and the modes are identical.
    #[test]
    fn snapshot_round_trip_stream1() {
        round_trip(include_bytes!("../../tests/fixtures/stream1.raw"), 120, 40);
    }

    #[test]
    fn snapshot_round_trip_stream2() {
        round_trip(include_bytes!("../../tests/fixtures/stream2.raw"), 100, 30);
    }

    fn round_trip(raw: &[u8], cols: u16, rows: u16) {
        let mut a = Screen::new(rows, cols);
        a.feed(raw);
        let snap = a.snapshot();

        let mut b = Screen::new(rows, cols);
        b.feed(&snap);

        // Cell-by-cell comparison.
        let ga = a.cell_grid();
        let gb = b.cell_grid();
        assert_eq!(ga.len(), gb.len(), "grid length mismatch");
        for (i, (ca, cb)) in ga.iter().zip(gb.iter()).enumerate() {
            let row = i / cols as usize;
            let col = i % cols as usize;
            // Compare char and display-relevant flags; ignore internal layout flags.
            let flags_a = ca.3 & DISPLAY_FLAGS;
            let flags_b = cb.3 & DISPLAY_FLAGS;
            assert_eq!(
                (ca.0, ca.1, ca.2, flags_a),
                (cb.0, cb.1, cb.2, flags_b),
                "cell mismatch at row={row} col={col}"
            );
        }

        // Cursor and modes must round-trip exactly.
        assert_eq!(a.cursor(), b.cursor(), "cursor mismatch");
        assert_eq!(a.modes(), b.modes(), "modes mismatch");
    }

    /// Wide characters and emoji occupy two columns; the spacer cell must
    /// render as a blank (not a second copy of the char) and the ratatui
    /// buffer must contain the right characters.
    #[test]
    fn wide_chars_render() {
        // 'Ａ' is a full-width ASCII variant (U+FF21), unicode width = 2.
        // '🦀' (crab emoji) is also width-2.
        let input = b"\x1b[2J\x1b[H\xef\xbc\x81\xf0\x9f\xa6\x80";
        let mut s = Screen::new(4, 20);
        s.feed(input);

        let mut buf = Buffer::empty(Rect::new(0, 0, 20, 4));
        s.render(Rect::new(0, 0, 20, 4), &mut buf);

        // Column 0: '！' (full-width exclamation, U+FF01)
        // Column 2: '🦀'
        // Columns 1 and 3 are spacer cells — rendered as space (blank).
        let cell0 = buf.cell((0, 0)).unwrap();
        let cell1 = buf.cell((1, 0)).unwrap();
        let cell2 = buf.cell((2, 0)).unwrap();
        let cell3 = buf.cell((3, 0)).unwrap();

        assert_eq!(cell0.symbol(), "\u{FF01}", "expected full-width ！ at col 0");
        assert_eq!(cell1.symbol(), " ", "spacer at col 1 should be blank");
        assert_eq!(cell2.symbol(), "🦀", "expected crab at col 2");
        assert_eq!(cell3.symbol(), " ", "spacer at col 3 should be blank");
    }

    /// OSC 0 / OSC 2 title sequences are captured and exposed via `title()`.
    #[test]
    fn title_capture() {
        let mut s = Screen::new(24, 80);
        // OSC 0 sets icon name + window title; OSC 2 sets window title only.
        s.feed(b"\x1b]0;Hello World\x07");
        assert_eq!(s.title().as_deref(), Some("Hello World"));

        s.feed(b"\x1b]2;New Title\x1b\\");
        assert_eq!(s.title().as_deref(), Some("New Title"));
    }

    /// `take_bell()` returns `true` once per BEL, then `false` until the next BEL.
    #[test]
    fn bell_take() {
        let mut s = Screen::new(24, 80);
        assert!(!s.take_bell());
        s.feed(b"\x07"); // BEL
        assert!(s.take_bell());
        assert!(!s.take_bell()); // consumed
    }

    /// Colors emitted by `emit_sgr` round-trip through `Screen::feed`.
    #[test]
    fn truecolor_snapshot() {
        let mut s = Screen::new(4, 20);
        // Set a truecolor fg (red), then write a character.
        s.feed(b"\x1b[38;2;255;0;0mX\x1b[0m");
        let snap = s.snapshot();
        let mut s2 = Screen::new(4, 20);
        s2.feed(&snap);
        let grid = s2.cell_grid();
        // Cell (0,0) should have fg = Spec(255,0,0).
        assert_eq!(grid[0].1, Color::Spec(Rgb { r: 255, g: 0, b: 0 }));
        assert_eq!(grid[0].0, 'X');
    }

    /// **Fable M5 – SGR continuation state.** Feed `ESC[31mA` (red 'A') into
    /// screen A, take a snapshot, then feed 'B' into BOTH A and a fresh screen
    /// B that received the snapshot. The 'B' character must be red in both.
    #[test]
    fn snapshot_sgr_continuation_state() {
        let mut a = Screen::new(4, 20);
        // Write a red 'A' but do NOT reset SGR — cursor is now after 'A'.
        a.feed(b"\x1b[31mA");

        // Take snapshot: the snapshot must re-emit the active SGR (red).
        let snap = a.snapshot();

        // Feed 'B' into the original screen (same state as before snapshot).
        a.feed(b"B");

        // Replay snapshot into a fresh screen, then feed 'B'.
        let mut b = Screen::new(4, 20);
        b.feed(&snap);
        b.feed(b"B");

        let ga = a.cell_grid();
        let gb = b.cell_grid();

        // Column 0 = 'A' (red) in both.
        assert_eq!(ga[0].0, 'A', "a: col 0 should be 'A'");
        assert_eq!(gb[0].0, 'A', "b: col 0 should be 'A'");

        // Column 1 = 'B' — must be red (NamedColor::Red) in BOTH screens.
        let red = Color::Named(NamedColor::Red);
        assert_eq!(ga[1].0, 'B', "a: col 1 should be 'B'");
        assert_eq!(ga[1].1, red, "a: 'B' must be red (SGR continuation)");
        assert_eq!(gb[1].0, 'B', "b: col 1 should be 'B'");
        assert_eq!(gb[1].1, red, "b: 'B' must be red (SGR continuation from snapshot)");
    }

    /// **Fable M5 – cursor position always emitted.** Even with a hidden
    /// cursor, the snapshot must place it at the real position so that
    /// further bytes appended to the snapshot render at the right location.
    #[test]
    fn snapshot_cursor_position_when_hidden() {
        let mut a = Screen::new(4, 20);
        // Move cursor to (row=1, col=5), then hide it.
        a.feed(b"\x1b[2;6H\x1b[?25l");
        let snap = a.snapshot();

        // The snapshot bytes must include ESC[2;6H (row+1=2, col+1=6).
        // We search as a substring.
        let snap_str = String::from_utf8_lossy(&snap);
        assert!(
            snap_str.contains("\x1b[2;6H"),
            "snapshot must contain ESC[2;6H for hidden cursor at row=1 col=5; got: {snap_str:?}"
        );

        // After replay + 'X', X must appear at col=5 row=1.
        let mut b = Screen::new(4, 20);
        b.feed(&snap);
        b.feed(b"X");
        let grid = b.cell_grid();
        // row=1, col=5 → index = 1*20 + 5 = 25
        assert_eq!(grid[25].0, 'X', "X must land at row=1 col=5 after snapshot replay");
    }
}
